/*
 * Handles all the Linked List Creations
 */
public class Node {
    protected String username;// Stores the Username
    protected long accno;// Stores the Random Account Number generated by the system.
    protected String hash_pin;// Stores the mPIN in "#Hashed#" form.
    protected double balance;// Stores the amount deposited/transacted from another user.
    protected String arr[] = new String[100];// Transaction History array.
    protected int front, rear;// Stores the front & rear value for the transaction history queue.
    protected byte request; // Stores request value. Updates according to Manager's response.
    protected String query; // Stores the "new" username that the user requests to be changed.
    protected String upload_file; // Stores the String for Aadhar upload.
    protected int number_of_mpin_attempts; // Stores the number of consecutive MPIN attempts.
    protected String mail_id;// Stores the Mail ID of the user. Can be used for Login, Instead of Account
                             // Number. (UPdate).
    protected Node next;// Stores the next memory address for the next Node.

    Node() {
        username = "";
        accno = 0L;
        hash_pin = "";
        balance = 0.0d;
        front = 0;
        rear = 0;
        request = 0;
        query = "";
        upload_file = "";
        number_of_mpin_attempts = 3;// by default number of set attempts for the user
        mail_id = "";
        next = null;
    }
}
